name: Infra
description: ""
mailing_list: ""
maintainers:
  - gitcode_id: georgecao
    name: 曹志
    organization: huawei
    email: george.cao@huawei.com
repositories:
  - repo:
      - boostkit/infra
      - boostkit/community
    committers:
      - gitcode_id: yao-xiaobai
        name: 姚孝添
        organization: huawei
        email: 176253319000@163.com
      - gitcode_id: juneuu
        name: 陈丽君
        organization: huawei
        email: chenlijun42@huawei.com
      - gitcode_id: lauyarn
        name: 刘阳
        organization: huawei
        email: liuyang645@huawei.com
      - gitcode_id: zwjsec
        name: 翟文杰
        organization: huawei
        email: zhaiwenjie1@huawei.com